# Generated by Django 2.2.16 on 2023-01-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20221226_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Добавьте изображение для поста', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
