# Generated by Django 2.2.16 on 2023-06-19 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20230609_1012'),
        ('posts', '0011_auto_20230118_0616'),
    ]

    operations = [
    ]
